In [8]:
from math import cos, sin, atan2, pi

angle = 60 * pi / 180

q = {
    'x': 0.0,
    'y': 0.0,
    'z': sin(angle/2),
    'w': cos(angle/2)
}
    

In [9]:
print('quaternion: %s' % q)

quaternion: {'x': 0.0, 'y': 0.0, 'z': 0.49999999999999994, 'w': 0.8660254037844387}


In [10]:
recompute_angle = atan2(q['z'], q['w']) * 2
print('yaw angle extracted is %s' % (recompute_angle * 180 / pi))

yaw angle extracted is 59.99999999999999


In [14]:
from scipy.spatial.transform import Rotation as R
import numpy as np

In [28]:
r = R.from_quat([0, 0, np.sin(angle/2), np.cos(angle/2)])

In [29]:
r.as_matrix()

array([[ 0.5      , -0.8660254,  0.       ],
       [ 0.8660254,  0.5      ,  0.       ],
       [ 0.       ,  0.       ,  1.       ]])

In [30]:
r.as_quat()

array([0.       , 0.       , 0.5      , 0.8660254])

In [31]:
r.as_euler('XYZ', True)

array([ 0.,  0., 60.])